Nc news 5
royr5/nc-news pull request #5
Opened 2023-11-21 14:01 UTC by royr5

add GET /api/articles endpoint

2023-11-21 15:51 UTC, johnhutcheon requested changes
Hey Roshan, just a few changes need to be made here please...
- Each endpoint should have it's own controller and model. We shouldn't be re-using them for different endpoints.
Please refactor and resubmit. 👍

2023-11-21 15:51 UTC, johnhutcheon commented on __tests__/index.test.js
> +        expect(arr.length).toBe(5);
Nice work checking the length before forEach 👍

2023-11-21 15:51 UTC, johnhutcheon commented on __tests__/index.test.js
> +        expect(arr).toBeSortedBy("created_at", { descending: true });
Well done with this line too! 🙌

2023-11-21 15:51 UTC, johnhutcheon commented on __tests__/index.test.js
> +  test("404: respond with an error message saying path is not found", () => {
This test isn't specific to api/articles. It should either be in it's own describe block or removed.

2023-11-21 15:51 UTC, johnhutcheon commented on app.js
>  app.get("/api/articles/:article_id", getArticles);
We shouldn't be re-using controllers. `getArticles` should only be the controller for `api/articles`. You should have a separate controller for `/api/articles/:article_id`, preferably called something like `getSingleArticle` 👍

2023-11-22 09:51 UTC, nickkagame approved these changes
Nice work Roshan

2023-11-22 09:52 UTC, merged